### ISSUE TITLE
Running ./provision-vagrant fails on aa

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#48] opened 2016-03-05 00:04 UTC
Hello,

I've been trying to get a test environment going using the current code base, but keep getting the following error when I run it.
```
TASK [aa : wait for aa to start] ***********************************************
fatal: [192.168.66.79]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for 127.0.0.1:9198"}

```
Accessing https://vm.openconext.org/ gives:
```
503 Service Unavailable

No server is available to handle this request.
```

I've poked around to see if I can figure it out, but haven't been able to yet..  Any help would be great!

Thanks,
Andrew

Here's an analysis on different pieces relating to 'aa'
```
[root@apps current]# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 08:00:27:68:75:FA
          inet addr:192.168.66.79  Bcast:192.168.66.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe68:75fa/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:125468 errors:0 dropped:0 overruns:0 frame:0
          TX packets:47958 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:125161937 (119.3 MiB)  TX bytes:4089058 (3.8 MiB)
```

According to the aa.conf file, the port should be running locally on the apps server:
```
[root@apps current]# cat /etc/httpd/conf.d/aa.conf  |grep 9198
    ProxyPass /aa/api http://localhost:9198/ retry=0
    ProxyPassReverse /aa/api http://localhost:9198/
```

```
[root@apps current]# /etc/init.d/aa status
aa (pid 30497) is running...
```

```
[root@apps current]# telnet 127.0.0.1 9198
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

This is what I'm seeing in the  /var/log/aa/aa.log file:
```
2016-03-05 00:23:33,876 DEBUG [pool-4-thread-1] a.s.UrlResourceServiceRegistry:34 - Starting refreshing SP metadata.
2016-03-05 00:23:33,877 DEBUG [pool-4-thread-1] a.s.UrlResourceServiceRegistry:51 - Fetching SP metadata entries from https://multidata.vm.openconext.org/service-providers.json
2016-03-05 00:23:33,879 ERROR [pool-4-thread-1] a.s.UrlResourceServiceRegistry:68 - Error in refreshing metadata
java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json
        at aa.serviceregistry.ClassPathResourceServiceRegistry.readValue(ClassPathResourceServiceRegistry.java:80) ~[aa-server-1.0.1-20160302.080912-1.jar!/:1.0.1-SNAPSHOT]
        at aa.serviceregistry.ClassPathResourceServiceRegistry.parseEntities(ClassPathResourceServiceRegistry.java:57) ~[aa-server-1.0.1-20160302.080912-1.jar!/:1.0.1-SNAPSHOT]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_71]
        at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[na:1.8.0_71]
        at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[na:1.8.0_71]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_71]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_71]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_71]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_71]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_71]
        at aa.serviceregistry.ClassPathResourceServiceRegistry.initializeMetadata(ClassPathResourceServiceRegistry.java:36) ~[aa-server-1.0.1-20160302.080912-1.jar!/:1.0.1-SNAPSHOT]
        at aa.serviceregistry.UrlResourceServiceRegistry.initializeMetadata(UrlResourceServiceRegistry.java:58) ~[aa-server-1.0.1-20160302.080912-1.jar!/:1.0.1-SNAPSHOT]
        at aa.serviceregistry.UrlResourceServiceRegistry.refreshMetataData(UrlResourceServiceRegistry.java:66) ~[aa-server-1.0.1-20160302.080912-1.jar!/:1.0.1-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_71]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_71]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_71]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_71]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_71]
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840) ~[na:1.8.0_71]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_71]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_71]
        at aa.serviceregistry.BasicAuthenticationUrlResource.getInputStream(BasicAuthenticationUrlResource.java:32) ~[aa-server-1.0.1-20160302.080912-1.jar!/:1.0.1-SNAPSHOT]
        at aa.serviceregistry.ClassPathResourceServiceRegistry.readValue(ClassPathResourceServiceRegistry.java:78) ~[aa-server-1.0.1-20160302.080912-1.jar!/:1.0.1-SNAPSHOT]
        ... 19 common frames omitted
```

No service listening on port 9198:
```
[root@apps current]# netstat -ln |grep 9198
[root@apps current]# netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State
tcp        0      0 0.0.0.0:11211               0.0.0.0:*                   LISTEN
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN
tcp        0      0 127.0.0.1:9876              0.0.0.0:*                   LISTEN
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN
tcp        0      0 0.0.0.0:42939               0.0.0.0:*                   LISTEN
tcp        0      0 0.0.0.0:389                 0.0.0.0:*                   LISTEN
tcp        0      0 0.0.0.0:3306                0.0.0.0:*                   LISTEN
tcp        0      0 :::9291                     :::*                        LISTEN
tcp        0      0 :::11211                    :::*                        LISTEN
tcp        0      0 :::9196                     :::*                        LISTEN
tcp        0      0 :::9197                     :::*                        LISTEN
tcp        0      0 :::9199                     :::*                        LISTEN
tcp        0      0 :::111                      :::*                        LISTEN
tcp        0      0 :::22                       :::*                        LISTEN
tcp        0      0 ::1:25                      :::*                        LISTEN
tcp        0      0 :::33856                    :::*                        LISTEN
tcp        0      0 :::389                      :::*                        LISTEN
tcp        0      0 :::9190                     :::*                        LISTEN
tcp        0      0 :::9191                     :::*                        LISTEN
tcp        0      0 :::9290                     :::*                        LISTEN
udp        0      0 0.0.0.0:111                 0.0.0.0:*
udp        0      0 192.168.66.79:123           0.0.0.0:*
udp        0      0 10.0.2.15:123               0.0.0.0:*
udp        0      0 127.0.0.1:123               0.0.0.0:*
udp        0      0 0.0.0.0:123                 0.0.0.0:*
udp        0      0 0.0.0.0:60805               0.0.0.0:*
udp        0      0 0.0.0.0:705                 0.0.0.0:*
udp        0      0 0.0.0.0:68                  0.0.0.0:*
udp        0      0 0.0.0.0:11211               0.0.0.0:*
udp        0      0 0.0.0.0:724                 0.0.0.0:*
udp        0      0 :::111                      :::*
udp        0      0 fe80::a00:27ff:fe68:75fa:123 :::*
udp        0      0 fe80::a00:27ff:fe5e:ac7:123 :::*
udp        0      0 ::1:123                     :::*
udp        0      0 :::123                      :::*
udp        0      0 :::34307                    :::*
udp        0      0 :::46738                    :::*
udp        0      0 :::54814                    :::*
udp        0      0 :::60959                    :::*
udp        0      0 :::33956                    :::*
udp        0      0 :::54316                    :::*
udp        0      0 :::60590                    :::*
udp        0      0 :::40880                    :::*
udp        0      0 :::705                      :::*
udp        0      0 :::48453                    :::*
udp        0      0 :::11211                    :::*
```

**Comment by precurse** [comment] 2016-03-05 00:10
What made me point to aa (other than the error), was this in the ansible playbooks:

```
- name: start the aa service
  service: name=aa state=started enabled=yes
  ignore_errors: true

- name: wait for aa to start
  wait_for: connect_timeout=30 port={{ springapp_tcpport }} state=started
```
Which points to: springapp_tcpport: 9198   in https://github.com/OpenConext/OpenConext-deploy/blob/572e11b5de0a7957851f927383644c7a9a0c30f7/roles/aa/vars/main.yml

**Comment by quartje** [comment] 2016-03-07 07:57
Hi Andrew,

This specific error should be fixed in the commit that has been done last Friday. 
The aa component is dependent on the metadata-exporter component. That has been fixed, and aa should start up without complaining now!

**Comment by precurse** [comment] 2016-03-07 20:42
Thanks for the help.

I just pulled the latest source, but seem to be getting the same error as before.  I blew away all of my Virtualbox VMs, and started with a fresh source tree.  Everything seems to build fine, except when it tries to provision the aa role, which I get the same error waiting for 127.0.0.1:9198.

I found an easy way to reproduce it (without having to do a full rebuild each time):
`./provision-single-component vm root secrets/vm.yml aa`
```TASK [aa : wait for aa to start] ***********************************************
fatal: [192.168.66.79]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for 127.0.0.1:9198"}```

**Comment by precurse** [comment] 2016-03-07 22:48
It appears that aa seems to hang and eventually die entirely..  I've ran it manually to see, and this is what I'm seeing:

```root@apps aa]# /usr/lib/jvm/java-1.8.0/bin/java -Xms512m -Xmx512m -jar aa.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.2.RELEASE)



Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        ... 1 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'internalAggregationController' defined in URL [jar:file:/opt/aa/aa-server-1.0.1-20160302.080912-1.jar!/aa/control/InternalAggregationController.class]: Unsatisfied dependency expressed through constructor argument with index 3 of type [aa.serviceregistry.ServiceRegistry]: : Error creating bean with name 'urlResourceServiceRegistry' defined in class path resource [aa/serviceregistry/ServiceRegistryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [aa.serviceregistry.ServiceRegistry]: Factory method 'urlResourceServiceRegistry' threw exception; nested exception is java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json?includeTest=true; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urlResourceServiceRegistry' defined in class path resource [aa/serviceregistry/ServiceRegistryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [aa.serviceregistry.ServiceRegistry]: Factory method 'urlResourceServiceRegistry' threw exception; nested exception is java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json?includeTest=true
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at aa.Application.main(Application.java:12)
        ... 6 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urlResourceServiceRegistry' defined in class path resource [aa/serviceregistry/ServiceRegistryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [aa.serviceregistry.ServiceRegistry]: Factory method 'urlResourceServiceRegistry' threw exception; nested exception is java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json?includeTest=true
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 25 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [aa.serviceregistry.ServiceRegistry]: Factory method 'urlResourceServiceRegistry' threw exception; nested exception is java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json?includeTest=true
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 38 more
Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json?includeTest=true
        at aa.serviceregistry.ClassPathResourceServiceRegistry.readValue(ClassPathResourceServiceRegistry.java:80)
        at aa.serviceregistry.ClassPathResourceServiceRegistry.parseEntities(ClassPathResourceServiceRegistry.java:57)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Collections$2.tryAdvance(Collections.java:4717)
        at java.util.Collections$2.forEachRemaining(Collections.java:4725)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at aa.serviceregistry.ClassPathResourceServiceRegistry.initializeMetadata(ClassPathResourceServiceRegistry.java:36)
        at aa.serviceregistry.UrlResourceServiceRegistry.<init>(UrlResourceServiceRegistry.java:46)
        at aa.serviceregistry.ServiceRegistryConfiguration.urlResourceServiceRegistry(ServiceRegistryConfiguration.java:31)
        at aa.serviceregistry.ServiceRegistryConfiguration$$EnhancerBySpringCGLIB$$b5e624fa.CGLIB$urlResourceServiceRegistry$1(<generated>)
        at aa.serviceregistry.ServiceRegistryConfiguration$$EnhancerBySpringCGLIB$$b5e624fa$$FastClassBySpringCGLIB$$ce94808c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
        at aa.serviceregistry.ServiceRegistryConfiguration$$EnhancerBySpringCGLIB$$b5e624fa.urlResourceServiceRegistry(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 39 more
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://multidata.vm.openconext.org/service-providers.json?includeTest=true
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at aa.serviceregistry.BasicAuthenticationUrlResource.getInputStream(BasicAuthenticationUrlResource.java:32)
        at aa.serviceregistry.ClassPathResourceServiceRegistry.readValue(ClassPathResourceServiceRegistry.java:78)
        ... 61 more```

**Comment by quartje** [comment] 2016-03-08 08:40
I am unable reproduce your issue here. I have pulled the latest OpenConext-deploy, and after running ./provision-vagrant everything runs fine here. 
The reason aa does not want to start is that the component metadata-exporter is not accessable.
Could you check the following for me?
- Is the proces metadata-exporter running?
- If so, can you check if /var/log/metadata-exporter/metadata-exporter.log contains an error?

**Comment by precurse** [comment] 2016-03-08 16:39
It looks like metadata-exporter is running:
```
[root@apps aa]# /etc/init.d/metadata-exporter status
metadata-exporter (pid 22873) is running...

[root@apps aa]# netstat -ln |grep 9199
tcp        0      0 :::9199                     :::*                        LISTEN
```

The log seems ok:
```
2016-03-07 23:20:47,612  INFO [main] me.Application:48 - Starting Application v1.0.1 on apps.vm.openconext.org with PID 22873 (/opt/metadata-exporter/metadata-exporter-1.0.1.jar started by metadata-exporter in /opt/metadata-exporter)
2016-03-07 23:20:47,618 DEBUG [main] me.Application:51 - Running with Spring Boot v1.3.2.RELEASE, Spring v4.2.4.RELEASE
2016-03-07 23:20:47,618  INFO [main] me.Application:670 - The following profiles are active: prod
2016-03-07 23:20:50,298 DEBUG [localhost-startStop-1] me.web.BasicAuthenticationFilter:177 - Initializing filter 'basicAuthenticationFilter'
2016-03-07 23:20:50,298 DEBUG [localhost-startStop-1] me.web.BasicAuthenticationFilter:202 - Filter 'basicAuthenticationFilter' configured successfully
2016-03-07 23:20:51,497  INFO [main] me.Application:57 - Started Application in 4.533 seconds (JVM running for 5.396)
```

I'll delete the vagrant VMs and source tree again to see if it works.

**Comment by precurse** [comment] 2016-03-08 22:57
On the load balancer, I'm seeing the following config under the haproxy config:
`server metadata_exporter_backend 192.168.66.79:616 cookie metadata_exporter_backend check inter 20000 fall 2 rise 2 maxconn 1024`  which would seem to indicate that metadata-explorer runs on port 616..  This is backed by this line: https://github.com/OpenConext/OpenConext-deploy/blob/af0f6b5a2d3241dd9445894d62075c59c3e969f4/group_vars/vm.yml#L608

However, on the apps host, It's showing up as port 9199:
```
[root@apps vagrant]# cat /opt/metadata-exporter/application.properties  |grep port
logging.config=file:///opt/metadata-exporter/logback.xml
server.port=9199
```
as seen in the Ansible role: https://github.com/OpenConext/OpenConext-deploy/blob/af0f6b5a2d3241dd9445894d62075c59c3e969f4/roles/metadata-exporter/vars/main.yml#L10

This is similar to the aa and pdp (haproxy config shows 6XX range port, while the ansible role shows 9XXX range).

Do you know if these are possibly conflicting? 

Thanks

**Comment by quartje** [comment] 2016-03-09 16:59
There is an Apache running on the app host that sits in between haproxy on the lb host and the java app. The java app listens on port 9199, apache on 616. 
Is that Apache vhost listening on port 616? Can you telnet to 192.168.66.79 on port 616 from the lb host?
Apache logs to /var/log/messages. Can you spot some errors there? ( grep Apache-Metadata-Exporter /var/log/messages)

**Comment by precurse** [comment] 2016-03-09 17:07
Well, it wasn't listening on the ports at first.  I gave Apache a restart and it looks like everything is working properly now. https://vm.openconext.org/  loads for me now!

Thanks for your help! Something strange is happening during the provisioning though if Apache isn't properly reading the config until a restart.  Weird.

**Closed** 2016-03-10 08:20 UTC
